openvinotoolkit/openvino_contrib

- modules/arm_plugin/src/transformations/arm_optimizations.cpp
Pass manager inside the `run_on_function` already changed the ngraph function and we don't have to return `true`
> Changed return value for ArmOptimizations run_on_function

- modules/arm_plugin/src/arm_plugin.cpp
Fixed:
```c++
src/runtime/Scheduler.cpp:74: !Scheduler::is_available(t)
```
> Fixed AC scheduler initialization

- modules/arm_plugin/cmake/features.cmake
- modules/arm_plugin/src/arm_converter/arm_converter_activation.cpp
- modules/arm_plugin/src/arm_converter/arm_converter_cumsum.cpp
- modules/arm_plugin/src/arm_converter/arm_converter_detection_output.cpp
- modules/arm_plugin/thirdparty/CMakeLists.txt
- More precise arch for apple m1
- Fixed deprecation warnings
- Disabled NHWC kernels which are not used by ARM plugin
> More precise arch for apple m1

- modules/arm_plugin/src/arm_converter/arm_converter_gather.cpp
Changed reference implementation for evaluate: introduced optional argument `batch_dims` for `v7::Gather` (in https://github.com/openvinotoolkit/openvino/pull/5088).  But for `v1::Gather` `batch_dims` is always 0.
> add default 0 value for batch_dims in v1::Gather reference

- modules/arm_plugin/src/arm_config.cpp
- modules/arm_plugin/src/arm_config.hpp
- modules/arm_plugin/src/arm_executable_network.cpp
- modules/arm_plugin/src/arm_executable_network.hpp
- modules/arm_plugin/src/arm_infer_request.cpp
- modules/arm_plugin/src/arm_infer_request.hpp
- modules/arm_plugin/src/arm_plugin.cpp
- modules/arm_plugin/src/arm_plugin.hpp
The main idea is to remove `cpp_interfaces/exception2status.hpp` include to be compatible with https://github.com/openvinotoolkit/openvino/pull/5419
> Updated headers for ARM plugin

- modules/arm_plugin/src/arm_converter/arm_converter.hpp
- modules/arm_plugin/src/arm_converter/arm_converter_nms.cpp
NMS conversion do not use deprecated `ngraph::Tensor::get_name`
> Fixed deprecation warnings

- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/reshape.cpp
Related: https://github.com/openvinotoolkit/openvino/pull/5648
Ticket: 
- *57975*
- *45956*
> Update SLT for reshape OP to be able pass `-1` as axis size

- modules/arm_plugin/tests/functional/conformance/skip_configs/skip_config_arm.lst
The test Broadcast_748166 is going to be temporarily skipped until the team is found the cause of its 5 hrs execution time.
> Skip Broadcast_748166 test

- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/convolution_backprop_data.cpp
Align ConvolutionBackprop SLT with new API provided in OV which is using output_padding attribute and output_shape input.
> Align SLT with new API provided in OV with output_padding support

- modules/arm_plugin/tests/functional/conformance/skip_configs/skip_config_arm.lst
Disable 2 more tests which take ~ 3 hrs to execute.
> Skip conformance tests

- modules/arm_plugin/src/arm_converter/arm_converter_convert.cpp
- modules/arm_plugin/src/arm_infer_request.cpp
- modules/arm_plugin/src/opset/quantize.cpp
- modules/arm_plugin/src/opset/quantize.hpp
- modules/arm_plugin/src/opset/util.cpp
- modules/arm_plugin/src/opset/utils.hpp
- modules/arm_plugin/src/transformations/arm_optimizations.cpp
- modules/arm_plugin/src/transformations/quantize_fusion.cpp
- modules/arm_plugin/src/transformations/quantize_fusion.hpp
- modules/arm_plugin/tests/functional/shared_tests_instances/low_precision_transformations/arm_convolution.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/low_precision_transformations/arm_group_convolution.cpp
* Arm Compute does not support per channel quantization on output tensors of convolution. So we have to move scales to weights quantization info and offset to biases.
* ArmQuantize is applied to separate channels in case of per-channel quantization
* Dequantiztion operations are not converted into ArmDequanitze in case of per-channel dequantization
> Enabled quantized MobileNetV2

- modules/arm_plugin/src/arm_converter/arm_converter_fake_quantize.cpp
- drop `v0` namespace after OV cleanup
- *60603*
- https://github.com/openvinotoolkit/openvino/pull/6810
- https://github.com/openvinotoolkit/openvino_contrib/pull/178
> get back with fake_quantize original call after cleanup in OV

- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/convolution_backprop_data.cpp
Moving back to previous ConvolutionBackpropDataLayerTest class name for ConvolutionBackprop SLT.
> Moving back to previous ConvolutionBackpropDataLayerTest class name.

- modules/arm_plugin/tests/functional/shared_tests_instances/low_precision_transformations/convolution_transformation.cpp
Change 16 levels to 14 levels in tests on incorrectness due to 16 levels support in LPT.
> [LPT] ARM convolution tests change

- .ci/azure/linux.yml
- modules/mo_pytorch/test/run_tests.py
We cannot use project without license. Please track https://github.com/cszn/USRNet/issues/41
> [MO] Remove USRNet until they publish license

- modules/mo_pytorch/setup.py
Recently model-optimizer in OpenVINO repohas been moved to another directory, see: https://github.com/openvinotoolkit/openvino/pull/7708
> Fix model-optimizer path in mo_pytorch setup.py

- modules/arm_plugin/armplg_build.sh
Some flags have been added and modified according to internal CI.
> [ARM Plugin] Use new OV python bindings location in plugin build script

- modules/arm_plugin/Dockerfile.RPi64_focal
- modules/arm_plugin/README.md
This docker image is the same as for 18 ubuntu except for sources.list content.
I tested it on my 20.04, it works fine, only python 3.7 needs to be installed manually (20.04 comes with 3.8).
> [ARM Plugin] Ubuntu 20 support

- modules/arm_plugin/tests/functional/shared_tests_instances/skip_tests_config.cpp
Looks like the issue described in 72140 still reproduces on the same test case, but without '_' postfix
> Fix the skip pattern for hanging ARM test

- modules/java_api/org/intel/openvino/IECore.java
https://dev.azure.com/openvinoci/dldt/_build/results?buildId=284701&view=logs&j=a82d9e72-1de4-5bd6-c188-90296135479e&t=79340282-cc49-53b9-a234-48d22cf6b121:
```
/Users/runner/work/1/_w/install_pkg/runtime/lib/intel64:
total 208936
drwxr-xr-x  18 runner  staff       576 Feb 18 13:07 .
drwxr-xr-x   3 runner  staff        96 Feb 18 13:07 ..
-rwxr-xr-x   1 runner  staff    231312 Feb 18 13:07 libinference_engine_java_api.dylib
-rwxr-xr-x   1 runner  staff  20606672 Feb 18 13:07 libopenvino.dylib
-rwxr-xr-x   1 runner  staff    466976 Feb 18 13:07 libopenvino_auto_batch_plugin.so
-rwxr-xr-x   1 runner  staff    609136 Feb 18 13:07 libopenvino_auto_plugin.so
-rwxr-xr-x   1 runner  staff    272000 Feb 18 13:07 libopenvino_c.dylib
-rwxr-xr-x   1 runner  staff   2153496 Feb 18 13:07 …
```
> [Java] libov_runtime.dylib renamed to libopenvino.dylib on Mac

- modules/arm_plugin/tests/functional/shared_tests_instances/skip_tests_config.cpp
The hang described in reproduces in issue 72140 also reproduces on smoke_BehaviorTests/OVInferRequestCallbackTests.canStartSeveralAsyncInsideCompletionCallbackWithSafeDtor/targetDevice=CPU_configItem=NUM_STREAMS_AUTO test case as well
> Skip more canStartSeveralAsyncInsideCompletionCallbackWithSafeDtor cases

- .ci/azure/linux.yml
- .ci/azure/windows.yml
Ticket 61954
https://dev.azure.com/openvinoci/dldt/_build/results?buildId=288052&view=logs&j=c66b862c-dbaa-5827-5973-496890707eb5&t=0f6a71b9-1318-5ab5-30ad-a6e7f3c41df2&l=448
```
Unexpected exception thrown.
org.gradle.internal.remote.internal.MessageIOException: Could not write '/127.0.0.1:51363'.
at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:140)
at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionDispatch.run(MessageHub.java:331)
at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at …
```
> Java Gradle update

- modules/arm_plugin/src/transformations/arm_optimizations.cpp
[SoftMax_8.md](https://github.com/openvinotoolkit/openvino/blob/master/docs/ops/activation/SoftMax_8.md)
Downgrade transformation is used because arm_compute::NESoftmaxLayer doesn't support axis negative value
> [ARM Plugin] added softmax-v8 downgrade transformation

- modules/arm_plugin/src/transformations/arm_optimizations.cpp
- *Introduce new granularity attribute instead of OperationPerTensorQuantizationRestriction*
- *73725*
OpenVINO PR: https://github.com/openvinotoolkit/openvino/pull/11330
product-config PR: https://github.com/intel-innersource/frameworks.ai.openvino.ci.product-configs/pull/1055
> [LPT] Introduce new granularity attribute instead of OperationPerTensorQuantizationRestriction

- modules/optimum/optimum/intel/nncf/patches/trainer_4.11.0.patch
- modules/optimum/optimum/intel/nncf/patches/trainer_4.9.1.patch
Fix error that occured when training without nncf_config:
> [openvino-optimum] Initialize Trainer.compression_ctrl

- .github/workflows/test_optimum.yml
- modules/optimum/optimum/intel/nncf/patches/trainer_4.11.0.patch
- modules/optimum/optimum/intel/nncf/patches/trainer_4.9.1.patch
- modules/optimum/optimum/intel/openvino/modeling_ov_utils.py
- modules/optimum/setup.py
- modules/optimum/tests/openvino/test_modeling_ov_auto.py
- modules/optimum/tests/openvino/utils.py
- Add token_type_ids for PyTorch models. This fixes an accuracy issue with some BERT models.
- Add accuracy check tests (would catch accuracy issue fixed by adding token_type_ids)
- Get output names for QA models from model instead of hardcoding (required for NNCF models unless users manually set the expected output names)
- Use ONNX opset_version 12
- Add datasets to [nncf] and [all] requirements
token_type_ids not added to TensorFlow models yet - that requires more testing and tests and should be fixed in a future PR. Added a #TODO comment to TF model loading for now.
requirements could be improved further to distinguish between nncf and all. You need datasets for NNCF examples though, and it's a simple library - it is good to have it installed by default with nncf too.
> [openvino-optimum] Fix BERT accuracy issue and other updates

- modules/java_api/cpp/core.cpp
- modules/java_api/cpp/openvino_java.hpp
- modules/java_api/org/intel/openvino/Core.java
https://github.com/openvinotoolkit/openvino_contrib/issues/420
> [JAVA] add Core constructor

- modules/arm_plugin/dockerfiles/Dockerfile.RPi32_buster
- modules/arm_plugin/dockerfiles/Dockerfile.RPi32_stretch
- modules/arm_plugin/dockerfiles/Dockerfile.RPi64_bionic
- modules/arm_plugin/dockerfiles/Dockerfile.RPi64_focal
- modules/arm_plugin/scripts/arm_cpu_plugin_build.sh
- Enable python wheel package build during cross-compilation for arm64
- 89936
> Enable cross-compilation for arm64

- modules/nvidia_plugin/src/transformer/bidirectional_lstm_sequence_composition.cpp
It's needed to unlock CI of https://github.com/openvinotoolkit/openvino/pull/13469. Problem occurred once _implicit_ inclusions where removed from some other header file (which didn't need that).
> [nvidia] Avoid implicit inclusions

- modules/java_api/CMakeLists.txt
- modules/java_api/tests/compatibility/IECoreTests.java
Gently skip `OpenVINODeveloperPackage` if not found. Actual for OpenVINO 2022.2
> [Java] Find OpenVINODeveloperPackage optionally

- modules/arm_plugin/scripts/install_build_dependencies.sh
`Parser/pgen` is not included in Python 3.10 (it is removed from CPython). Having it fails building Python 3.10.
> Remove `Parser/pgen`

- modules/arm_plugin/thirdparty/CMakeLists.txt
Build error message:
```
Using compilers:
CC  /opt/android/android-sdk.studio/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
CXX  /opt/android/android-sdk.studio/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
sh: line 1: /opt/android/android-sdk.studio/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar: No such file or directory
```
Details: https://github.com/android/ndk/issues/1802
> [ARM plugin]: build/android - workaround ANDROID_TOOLCHAIN_PREFIX

- modules/arm_plugin/src/arm_converter/arm_converter_mvn.cpp
Negative value means counting the in_shape dimensions from the back.
Partially fixes #428
Signed-off-by: Dmitry Ermilov <ermilovdimitry@gmail.com>
> [ARM Plugin] Fixed handling of negative axes values in MVN

- modules/arm_plugin/tests/functional/shared_tests_instances/skip_tests_config.cpp
OV tests updates (https://github.com/openvinotoolkit/openvino/commit/e075785486c0404551a73537d1d5c663a020a1cd) stop skipping some tests internally, so they need to be skipped explicitly by plugins.
> [ARM CPU plugin] Skip deviceID tests

- modules/arm_plugin/src/arm_converter/arm_converter.cpp
- modules/arm_plugin/src/arm_converter/arm_converter_interpolate.cpp
- modules/arm_plugin/src/arm_converter/arm_converter_slice.cpp
- modules/arm_plugin/src/opset/opset.hpp
- modules/arm_plugin/src/opset/slice_arm.cpp
- modules/arm_plugin/src/opset/slice_arm.hpp
- modules/arm_plugin/src/transformations/arm_optimizations.cpp
- modules/arm_plugin/src/transformations/convert_interpolate_arm.cpp
- modules/arm_plugin/src/transformations/convert_slice_arm.cpp
- modules/arm_plugin/src/transformations/convert_slice_arm.hpp
Add implementation of 'opset8::Slice' in ARM plugin through native 'NESlice'. Fixes #428
Signed-off-by: Dmitry Gurulev <dmitry.gurulev@gmail.com>
> [ARM plugin]: add 'Slice' implementation

- modules/arm_plugin/src/transformations/arm_optimizations.cpp
- modules/arm_plugin/src/transformations/conv_bias_fusion.cpp
- modules/arm_plugin/src/transformations/normalizel2_max_fusion.cpp
- modules/arm_plugin/src/transformations/quantize_fusion.cpp
Replaces `ngraph::pass` namespace with `ov::pass` for common/transformations stuff of ARM plugin.
> [ARM plugin] Use ov::pass namespace for transforamtions

- modules/arm_plugin/src/transformations/decompose_variadic_split.cpp
Fix this option: `In addition split_lengths can contain a single -1 element, which means, all remaining items along specified axis that are not consumed by other parts.`
https://docs.openvino.ai/latest/openvino_docs_ops_movement_VariadicSplit_1.html
> [ARM plugin] Fix result shapes calculation in VariadicSplit if split length == -1

- modules/arm_plugin/src/arm_converter/arm_converter_activation.cpp
- modules/arm_plugin/src/arm_converter/arm_converter_convert.cpp
- modules/arm_plugin/src/arm_converter/arm_converter_pool.cpp
Several fixes:
- Fallback to reference ops for non-float data type
- Swish check that beta parameter is available
- Return f32->i8 reference conversion that was removed by mistake in https://github.com/openvinotoolkit/openvino_contrib/pull/486
> [ARM plugin] Activation fixes

- modules/arm_plugin/src/arm_converter/arm_converter.cpp
- modules/arm_plugin/src/arm_converter/arm_converter_activation.cpp
- modules/arm_plugin/src/arm_converter/arm_converter_softmax.cpp
- modules/arm_plugin/src/transformations/arm_optimizations.cpp
> [ARM plugin] Update transformation set

- modules/arm_plugin/tests/functional/shared_tests_instances/skip_tests_config.cpp
These 2 tests fails because of https://github.com/openvinotoolkit/openvino/pull/14292 however root cause has not been found.
> [ARM CPU plugin] Skip Convert and ConvertLike tests FP16->U32

- modules/nvidia_plugin/include/nvidia/nvidia_config.hpp
- modules/nvidia_plugin/src/cuda_config.cpp
- modules/nvidia_plugin/src/cuda_config.hpp
- modules/nvidia_plugin/src/transformer/bidirectional_lstm_sequence_composition.cpp
- modules/nvidia_plugin/src/transformer/cuda_graph_transformer.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/tensor_iterator.cpp
PR with changes in OpenVINO https://github.com/openvinotoolkit/openvino/pull/13470
- *Remove `ConvertTensorIteratorToLSTMSequence` and `ConvertTensorIteratorToGRUSequence` from NV plugin since `ConvertTensorIteratorToSequence` is called from `MOCTransformations`*
- *Call `ConvertSequenceToTensorIterator` for unsupported LSTM and GRU sequences*
- *Remove `DISABLE_TENSORITERATOR_TRANSFORM` config parameter*
> [NVIDIA] Support changes in OpenVINO: TI via Sequence

- modules/nvidia_plugin/src/ops/interpolate_nearest.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/interpolate.cpp
- *Fix case when axis input of Interpolate is missing (default value [0,...,rank(data) - 1])*
> [NVIDIA] Fix case when axis input of Interpolate is missing

- modules/nvidia_plugin/src/cuda_executable_network.cpp
- modules/nvidia_plugin/src/cuda_plugin.cpp
- modules/nvidia_plugin/src/transformer/cuda_graph_transformer.cpp
- modules/nvidia_plugin/src/transformer/cuda_graph_transformer.hpp
- *Reuse common function `InferenceEngine::GetSupportedNodes` in `QueryNetwork`*
- *Refactor transformation pipeline to avoid transformation dubplication for exported model*
Relates:
PR with some fixes in HETERO part: https://github.com/openvinotoolkit/openvino/pull/13766
PR with fix for QN test: https://github.com/openvinotoolkit/openvino/pull/14601
> [NVIDIA] Reuse common function for query model

- modules/nvidia_plugin/src/ops/matmul.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/mat_mul.cpp
- *Fix MatMul shape broadcast when A rank is equal to B rank*
> [NVIDIA] Fix MatMul shape broadcast when A rank is equal to B rank

- .github/workflows/history_cuda.yml
Moving 'History CUDA' workload to be run on GitHub-hosted ubuntu-22.04 runner.
> 'History CUDA' move to ubuntu-22.04 runner

- modules/arm_plugin/src/transformations/decompose_variadic_split.cpp
The fix addresses the error `get_shape() must be called on a node with exactly one output`
> [ARM Plugin] Fix DecomposeVariadicSplit transformation if input node has more than 1 output

- modules/arm_plugin/src/transformations/decompose_variadic_split.cpp
Propagation of https://github.com/openvinotoolkit/openvino_contrib/pull/555
> [ARM Plugin] Fix DecomposeVariadicSplit transformation if input node has more than 1 output 

- modules/nvidia_plugin/tests/functional/skip_tests_config.cpp
*Disable some tests which are not working currently on CI. CUDNN 8.1.0 is installed currently where there is problem with CUDNN_RNN_ALGO_STANDARD implementation for RNN component*: https://github.com/openvinotoolkit/openvino_contrib/blob/ef910366978efc2508a514259286219fbc302d51/modules/nvidia_plugin/src/ops/rnn_components/rnn_cudnn_components.cpp#L410
*That's why CUDNN_RNN_ALGO_PERSIST_STATIC is used, but it leads to CUDNN_STATUS_NOT_SUPPORTED. Problem have to insvestigated, disable some tests temporarely*
Tickets:
- *[101753](https://jira.devtools.intel.com/browse/CVS-101753)*
> [NVIDIA] Disable some tests to pass CI

- modules/nvidia_plugin/src/cuda_plugin.cpp
- *Return device architecture for device specified by DEVICE_ID config (aligned with Intel GPU)*
```
[ INFO ] GPU.0
[ INFO ]        SUPPORTED_PROPERTIES: 
...
[ INFO ]                Immutable: DEVICE_ARCHITECTURE : GPU: v12.0.0
.
[ INFO ] GPU.1
[ INFO ]        SUPPORTED_PROPERTIES: 
...
[ INFO ]                Immutable: DEVICE_ARCHITECTURE : GPU: NVIDIA GeForce RTX 3090
[ INFO ] NVIDIA
[ INFO ]        SUPPORTED_PROPERTIES:
...
[ INFO ]                Immutable: DEVICE_ARCHITECTURE : NVIDIA: v8.6
```
> [NVIDIA]: return device architecture

- modules/arm_plugin/src/opset/quantize.hpp
- modules/arm_plugin/src/opset/utils.hpp
- modules/arm_plugin/src/transformations/quantize_fusion.cpp
- modules/arm_plugin/src/transformations/quantize_fusion.hpp
- modules/nvidia_plugin/src/ops/result.cpp
- modules/nvidia_plugin/src/transformer/bidirectional_lstm_sequence_composition.cpp
- modules/nvidia_plugin/src/transformer/concat_transformation.cpp
- modules/nvidia_plugin/src/transformer/cuda_fullyconnected_transformation.cpp
- modules/nvidia_plugin/src/transformer/matmul_transformations.cpp
- modules/nvidia_plugin/src/transformer/remove_duplicated_results_transformation.cpp
Signed-off-by: xuejun <Xuejun.Zhai@intel.com>
Tickets: 100091
Because variantImpl & variantwrapper related class/interfaces will be deprecated in PR: 15580
Remove the related reference to variant.hpp
> Remove the include about variant.hpp, which had been deprecated

- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/select.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/fake_quantize.cpp
Fix issue caused by https://github.com/openvinotoolkit/openvino/pull/15806
- Remove static const AutoBroadcastSpec NUMPY;
- Remove static const AutoBroadcastSpec NONE;
> [Remove APIs] Modify caused by remove static const AutoBroadcastSpec NUMPY/NONE

- modules/arm_plugin/thirdparty/CMakeLists.txt
- ARM compute uses std::threads, so we have to link Threads library
- Fixes for Windows to remove -fPIC, /MP for clang-cl compiler
> Link Threads library because of ARM Compute

- modules/arm_plugin/src/opset/pool_arm.hpp
Details:
- Deprecated ov::DiscreteTypeInfo member version
- Remove related reference or using about version
Tickets:
- 100091
> Modify OPENVINO_OP using, caused by deprecated version

- modules/nvidia_plugin/src/kernels/gather.cu
- modules/nvidia_plugin/src/ops/gather.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/gather.cpp
- *added `Gather-8` support (with negative indices)*
- 102832
> [NVIDIA] Add Gather-8 (negative indices) support

- modules/nvidia_plugin/include/nvidia/properties.hpp
- modules/nvidia_plugin/src/cuda_config.cpp
- modules/nvidia_plugin/src/cuda_config.hpp
- modules/nvidia_plugin/src/cuda_executable_network.cpp
- modules/nvidia_plugin/src/cuda_infer_request.cpp
- modules/nvidia_plugin/src/cuda_plugin.cpp
- modules/nvidia_plugin/src/transformer/cuda_graph_transformer.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/behavior/ov_executable_network/properties.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/behavior/ov_plugin/properties_tests.cpp
- modules/nvidia_plugin/tests/functional/skip_tests_config.cpp
- modules/nvidia_plugin/tests/unit/executable_network.cpp
- *Enable new property API for NVIDIA plugin*
- *Performance counters are turned off by default now*
- *ov::inference_precision and ov::hint::execution_mode are also supported, but default behaviour is not changed. Additional accuracy numbers are required to turn default precision to f16*
hello_query_device output:
```
[ INFO ] NVIDIA
[ INFO ]        SUPPORTED_PROPERTIES: 
[ INFO ]                Immutable: AVAILABLE_DEVICES : NVIDIA.0
[ INFO ]                Immutable: CACHING_PROPERTIES : DEVICE_ARCHITECTURE INFERENCE_PRECISION_HINT EXECUTION_MODE_HINT
[ INFO ]                Immutable: RANGE_FOR_STREAMS : 1 10
[ INFO ]                Immutable: RANGE_FOR_ASYNC_INFER_REQUESTS : 1 1 1
[ INFO ]                Immutable: DEVICE_ARCHITECTURE : NVIDIA: v8.6
[ INFO ]                Immutable: …
```
> [NVIDIA]: Enable new property API

- modules/nvidia_plugin/src/cuda_executable_network.cpp
- *Fixes OPERATION_BENCHMARK option reading according to new API provided by this PR: https://github.com/openvinotoolkit/openvino_contrib/pull/595*
> [NVIDIA] Fix OPERATION_BENCHMARK option reading according to new API

- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/interpolation.cpp
- modules/nvidia_plugin/src/ops/interpolate.cpp
- modules/nvidia_plugin/src/ops/interpolate_components/interpolate_components.cpp
- modules/nvidia_plugin/src/ops/interpolate_cubic.cpp
- modules/nvidia_plugin/src/ops/interpolate_linear.cpp
- modules/nvidia_plugin/src/ops/interpolate_nearest.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/interpolate.cpp
This PR is required to fix the build errors which started popping up after the changes introduced by this PR https://github.com/openvinotoolkit/openvino/pull/16162
The deprecated enum values are going to be removed and thus all usages need to be adjusted.
> [ARM] [CUDA] Interpolate - Cleanup of deprecated symbols usage

- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/interpolate.cpp
Changes to the deprecated symbols in the CUDA plugin. This PR contains changes which were not done in https://github.com/openvinotoolkit/openvino_contrib/pull/620 by mistake.
> [CUDA] Interpolate - Cleanup of deprecated symbols usage #2

- modules/nvidia_plugin/tests/functional/skip_tests_config.cpp
- *Skip LoadNetworkToDefaultDeviceNoThrow test to enable NVIDIA CI*
- *106454*
- *106628*
Depends on https://github.com/openvinotoolkit/openvino/pull/16507
> [NVIDIA] Skip LoadNetworkToDefaultDeviceNoThrow test

- modules/custom_operations/user_ie_extensions/sentence_piece/CMakeLists.txt
Now, after https://github.com/google/sentencepiece/pull/837 is merged, we can remove WA for MSVC runtime flags.
> Updated sentensepiece version

- modules/nvidia_plugin/src/cuda/event.hpp
- modules/nvidia_plugin/src/cuda/graph.cpp
- modules/nvidia_plugin/src/cuda/graph.hpp
- modules/nvidia_plugin/tests/unit/cuda/wrappers/graph.cpp
- modules/nvidia_plugin/tests/unit/cuda/wrappers/graph.cu
- modules/nvidia_plugin/tests/unit/cuda/wrappers/graph.cuh
- *cudaGraph_t C++ wrapper*
- *cudaGraphExec_t C++ wrapper*
- *GraphCapture C++ wrapper*
- *GraphCaptureScope C++ wrapper*
- *New CUDA::Event constructor which allows events creation with flags*
- *Tests which cover CUDA Graph API C++ wrappers functionality*
- *[CVS-108536](https://jira.devtools.intel.com/browse/CVS-108536)*
> [NVIDIA] CUDA Graph API C++ wrappers

- modules/nvidia_plugin/src/transformer/cuda_graph_transformer.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/behavior/infer_request/infer_request.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/gru_cell.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/lstm_cell.cpp
- modules/nvidia_plugin/tests/functional/skip_tests_config.cpp
- modules/nvidia_plugin/tests/unit/transformations/cuda_transformations_test.cpp
- *Fix failing unit and functional tests for FP16 precision on different hardware configurations*
- CVS-113390
> [NVIDIA] FP16 Test Fixes

- modules/nvidia_plugin/src/cuda_config.cpp
- modules/nvidia_plugin/src/cuda_plugin.cpp
- modules/nvidia_plugin/src/transformer/cuda_graph_transformer.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/behavior/infer_request/infer_request.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/behavior/ov_executable_network/properties.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/behavior/ov_plugin/properties_tests.cpp
- modules/nvidia_plugin/tests/unit/executable_network.cpp
- *Switch inference precision to f16 dy default*
- *Remove WA with pre-processing for ConvertPrecision since transformation was extended with new parameter which allow keep precision of inputs/outputs*
- *105052*
> [NVIDIA] Switch inference precision to f16 by default

- modules/nvidia_plugin/README.md
- modules/nvidia_plugin/include/nvidia/properties.hpp
- modules/nvidia_plugin/src/cuda_compiled_model.cpp
- modules/nvidia_plugin/src/cuda_config.cpp
- modules/nvidia_plugin/src/cuda_config.hpp
- modules/nvidia_plugin/src/ops/tensor_iterator.cpp
- modules/nvidia_plugin/src/ops/tensor_iterator.hpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/behavior/ov_executable_network/properties.cpp
- *Enable `use_cuda_graph` as default option for plugin*
- 115922
- https://github.com/openvinotoolkit/openvino_contrib/pull/686
> [NVIDIA] Enable `use_cuda_graph` as default option for plugin

- modules/nvidia_plugin/CMakeLists.txt
- *Fix problem with windows debug build:  if multiple CL.EXE write to the same .PDB file, please use /FS*
- 115171
> [NVIDIA] Fix for windows debug build

- modules/nvidia_plugin/src/ops/convolution_components/convolution_cudnn_components.cpp
- *Sets proper convolution math type according to the math type of the selected algo*
> [NVIDIA] Set proper math type for convolution

- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/average_finder.hpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/convolution.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/convolution_biasadd_activation.cpp
- modules/nvidia_plugin/tests/functional/skip_tests_config.cpp
- *Fix failing convolution single layer tests using `AverageFinder` class to find threshold based on average values of the output*
- https://github.com/openvinotoolkit/openvino_contrib/pull/702
- CVS-113390
> [NVIDIA] Convolution Test Fixes Using Average Threshold

- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/convolution_backprop_data.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/convolution_backprop_data_add.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/convolution_biasadd_activation.hpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/cuda_eltwise.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/fully_connected.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/gru_cell.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/gru_sequence.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/lstm_cell.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/lstm_sequence.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/range.cpp
- modules/nvidia_plugin/tests/unit/test_networks.hpp
- ngraph::builder::makeInputLayer function is being deleted from openvino repo. Exclude from contrib repo as well 
- ngraph::builder::makeParameter and ngraph::builder::makeDynamicParameter function is being deleted from openvino repo. Exclude from contrib repo as well
> Remove some builder functions usage

- modules/nvidia_plugin/src/transformer/concat_transformation.cpp
- modules/nvidia_plugin/src/transformer/fuse_conv_biasadd_activation.cpp
- modules/nvidia_plugin/src/transformer/fuse_matmul_add.cpp
- modules/nvidia_plugin/src/transformer/matmul_transformations.cpp
- *Cleanup legacy ExecGraphInfoSerialization::ORIGINAL_NAMES. Currently fused  names are used to fill ov::exec_model_info::ORIGINAL_NAMES in runtime graph*
> [NVIDIA] Cleanup legacy ExecGraphInfoSerialization::ORIGINAL_NAMES

- modules/nvidia_plugin/src/ops/detection_output.cpp
- modules/nvidia_plugin/src/transformer/cuda_graph_transformer.cpp
- modules/nvidia_plugin/src/transformer/detection_output_fix_input_types_transformation.cpp
- modules/nvidia_plugin/src/transformer/detection_output_fix_input_types_transformation.hpp
- modules/nvidia_plugin/tests/unit/transformations/detection_output_fix_input_types.cpp
- *DetectionOutput operation in NVIDIA plugin is missing a check to assure that all the input/output types are the same.
In case all types are FP16 but the 3rd input type is FP32 the operation result is incorrect.
This PR adds the proper check and a transformation to covert any inputs with incorrect type*
- 119127
- *According to DetectionOutput specification (https://docs.openvino.ai/2023.0/openvino_docs_ops_detection_DetectionOutput_1.html):
"The first tuple with batch_id equal to -1 means end of output."
So the implementation in NVIDIA plugin doesn't change the rest of the values in the output after the 1st '-1.0' value and all other values should be ignored.*
> [NVIDIA] DetectionOutput fix input types

- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/transpose_test.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/variadic_split.cpp
- *Move Transpose, VeriadicSplit layer tests to API 2.0*
- *111380*
> [NVIDIA] Move Transpose, VeriadicSplit layer tests to API 2.0

- modules/nvidia_plugin/CMakeLists.txt
- modules/nvidia_plugin/src/CMakeLists.txt
- modules/nvidia_plugin/tests/functional/CMakeLists.txt
Example of failure we want to fix https://github.com/openvinotoolkit/openvino/actions/runs/6462856711/job/17545338161?pr=20327
> Fixed compilation when building out of OV build tree

- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/convert.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/convert_color_common.hpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/convert_color_i420.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/convert_color_nv12.cpp
- *Move Convert, ConvertColorI420, ConvertColorNV12 tests to API2.0*
Depends on https://github.com/openvinotoolkit/openvino/pull/20227
- *111380*
> [NVIDIA] Move Convert, ConvertColorI420, ConvertColorNV12 tests to API2.0

- modules/nvidia_plugin/tests/unit/compile_model.cpp
- modules/nvidia_plugin/tests/unit/memory_manager/cuda_immutable_memory_block_builder_test.cpp
- modules/nvidia_plugin/tests/unit/memory_manager/cuda_memory_manager_test.cpp
- modules/nvidia_plugin/tests/unit/memory_manager/model/cuda_immutable_memory_model_builder_test.cpp
- modules/nvidia_plugin/tests/unit/memory_manager/model/cuda_memory_model_builder_test.cpp
Changes:
- Previously in release mode some of Unit Tests expected to crash with ASSERT_DEATH, but after switching to OPENVINO_ASSERT which always throws exception it is not anymore a case
- Updated MatMul test which not always converts to FP16
> [NVIDIA] Fix Unit Tests

- README.md
- modules/rust_api/README.md
This change adds documentation, but no code, to explain how one might use OpenVINO from Rust. This is a partial response to https://github.com/intel/openvino-rs/issues/70; there are more things that need to be done before we re-evaluate moving any code.
> Add references to Rust API

- modules/nvidia_plugin/src/cuda_compiled_model.cpp
- modules/nvidia_plugin/src/cuda_config.hpp
- modules/nvidia_plugin/src/cuda_infer_request.cpp
- modules/nvidia_plugin/src/cuda_plugin.cpp
- modules/nvidia_plugin/src/cuda_thread_pool.hpp
Change threading related interface from API 1.0 to 2.0 due to migration interface from API 1.0 to 2.0 in openvino. 
This PR must be merged before [PR21167](https://github.com/openvinotoolkit/openvino/pull/21167)
> Change threading related interface from API 1.0 to 2.0

- modules/custom_operations/user_ie_extensions/tokenizer/python/ov_tokenizer/hf_parser.py
- modules/custom_operations/user_ie_extensions/tokenizer/python/ov_tokenizer/tokenizer_pipeline.py
Explicitly use utf-8 to read json - Windows uses cp1252
Use i64 constant where needed - as_node returns i32 on Windows
> [Tokenizer] Fix Windows Related Bugs

- .ci/azure/linux.yml
- .ci/azure/mac.yml
- .ci/azure/windows.yml
- modules/custom_operations/user_ie_extensions/CMakeLists.txt
- modules/custom_operations/user_ie_extensions/tokenizer/python/openvino_tokenizers/__init__.py
Fixing https://dev.azure.com/openvinoci/dldt/_build/results?buildId=677156&view=logs&jobId=6c23757f-dbf6-510b-3bd6-0534daaa0edf&j=6c23757f-dbf6-510b-3bd6-0534daaa0edf&t=7d01fa6f-0d1f-5d8f-c395-ec4220521ec9
> [Tokenizers] Added LC_RPATH to additionally point to openvino's libs

- modules/custom_operations/pyproject.toml
Centos set CMAKE_INSTALL_LIBDIR to lib64,we need to prevent that.
> [TOKENIZERS] Set CMAKE_INSTALL_LIBDIR path 

- modules/custom_operations/pyproject.toml
- modules/custom_operations/user_ie_extensions/tokenizer/python/openvino_tokenizers/__init__.py
- modules/custom_operations/user_ie_extensions/tokenizer/python/openvino_tokenizers/cli.py
- modules/custom_operations/user_ie_extensions/tokenizer/python/openvino_tokenizers/constants.py
- modules/custom_operations/user_ie_extensions/tokenizer/python/openvino_tokenizers/convert_tokenizer.py
- modules/custom_operations/user_ie_extensions/tokenizer/python/openvino_tokenizers/hf_parser.py
- modules/custom_operations/user_ie_extensions/tokenizer/python/openvino_tokenizers/tokenizer_pipeline.py
```bash
usage: convert_tokenizer [-h] [-o OUTPUT] [--with-detokenizer] [--skip_special_tokens] [--use-fast-false] [--trust-remote-code]
[--tokenizer-output-type {i32,i64}] [--detokenizer-input-type {i32,i64}] [--streaming-detokenizer STREAMING_DETOKENIZER]
name
Converts tokenizers from Huggingface Hub to OpenVINO Tokenizer model.
positional arguments:
name                  The model id of a tokenizer hosted inside a model repo on huggingface.co or a path to a saved Huggingface tokenizer
directory
options:
-h, --help            show this help message and exit
-o OUTPUT, --output OUTPUT
Output directory
--with-detokenizer    Add a detokenizer model to the output
--skip_special_tokens
Produce detokenizer that will skip special tokens during decoding, similar to …
```
> [Tokenizer] Add CLI Tokenizer Converter

- modules/custom_operations/user_ie_extensions/tokenizer/python/openvino_tokenizers/__init__.py
Extended extension searching paths, using the following order
1) os.environ.get("OV_TOKENIZER_PREBUILD_EXTENSION_PATH")
2) in the same folder as init.py
3) user site-packages
4) system site-packages
> [TOKENIZERS] Extended extension searching paths

- modules/custom_operations/user_ie_extensions/calculate_grid.cpp
- modules/custom_operations/user_ie_extensions/complex_mul.cpp
- modules/custom_operations/user_ie_extensions/fft.cpp
- modules/custom_operations/user_ie_extensions/grid_sample.cpp
- modules/custom_operations/user_ie_extensions/sparse_conv.cpp
- modules/custom_operations/user_ie_extensions/sparse_conv_transpose.cpp
Use `ov::element` instead of 'ngraph::element` to fix build issues after removing `HostTensor` in openvinotoolkit/openvino#22146
> [custom operations] Use ov::element in custom operations module

- modules/nvidia_plugin/src/ops/convolution_components/convolution_components.cpp
- modules/nvidia_plugin/src/ops/convolution_components/convolution_components.hpp
Details:
Remove `InferPadding` as input node has static shapes and shape inference should calculate padding correctly. Padding can be just get and calculation should not be required.
The `InferPadding` depends on `infer_auto_padding` which is legacy implementation for shape inference and removed in [PR #22036](https://github.com/openvinotoolkit/openvino/pull/22036)
> [NVIDIA] Remove InferPadding from convolution

- modules/nvidia_plugin/src/transformer/nodes/fused_convolution_backprop_data.cpp
- modules/nvidia_plugin/src/transformer/nodes/fused_convolution_backprop_data.hpp
Deprecated function `ngraph::opset1::infer_conv_backprop_auto_padding` from OV core validation util is being removed in OpenVINO 2024.0 release in [PR 22152](https://github.com/openvinotoolkit/openvino/pull/22152). It's used by `FusedConvBackpropData::validate_and_infer_types()` though it's added in this PR into this class similar way as already present `infer_conv_backprop_output_spatial_shape` method.
> [NVIDIA] Add infer_conv_backprop_auto_padding func

- modules/nvidia_plugin/tests/unit/result.cpp
Remove API: Tensor(const element::Type& element_type, const PartialShape& pshape, const std::string& name)
> OV deprectaed ov::descriptor::Tensor construct with name

- modules/nvidia_plugin/src/cuda_compiled_model.cpp
Change the access to properties of executor config because the properties are changed to private in Openvino in [PR22414](https://github.com/openvinotoolkit/openvino/pull/22414)
> Preperties of executor config are changed to private

- modules/nvidia_plugin/src/ops/clamp_cudnn.cpp
`ngraph/util.hpp` is to be removed from OV code base so [`double_to_int`](https://github.com/openvinotoolkit/openvino/blob/0744509aba36432abf1c4cf3d89a464c13251727/src/core/include/ngraph/util.hpp#L270-L292) is copied into nvidia_plugin code.
CVS-130665
> [NVIDIA] Remove ngraph/util.hpp dependency

- modules/openvino_code/README.md
- modules/openvino_code/package-lock.json
- modules/openvino_code/package.json
- modules/openvino_code/shared/features.ts
- modules/openvino_code/shared/model.ts
- modules/openvino_code/side-panel-ui/src/components/sections/OverviewSection/OverviewSection.tsx
- modules/openvino_code/side-panel-ui/src/components/sections/ServerSection/ModelSelect/ModelSelect.tsx
Adding FIM support through deepseek-coder-1.3b-instruct and changed model names at Frontend
> [OPENVINO CODE] Added Fill-in-the-middle(FIM) support 

- modules/nvidia_plugin/src/error.cpp
Add ov::Exception wrapper to access its protected constructor.
> [NVIDIA] Add ov::Exception wrapper

- modules/java_api/src/test/java/org/intel/openvino/CoreTests.java
Fixed issue:
```
org.intel.openvino.CoreTests > testProperty FAILED
java.lang.Exception: 
InferenceEngineException: 
SetProperty: Exception from src/inference/src/cpp/core.cpp:216:
Exception from src/inference/src/dev/plugin.cpp:49:
Exception from src/plugins/intel_cpu/src/config.cpp:337:
NotFound: Unsupported property CPU_THROUGHPUT_STREAMS by CPU plugin.
at org.intel.openvino.Core.SetProperty(Native Method)
at org.intel.openvino.Core.set_property(Core.java:157)
at org.intel.openvino.CoreTests.testProperty(CoreTests.java:88)
```
> Use API 2.0 properties in Java tests

- modules/openvino_code/README.md
Modified Readme file to include changes related to Fill-in-the middle mode support
> [OPENVINO CODE] modify readme file to include fill-in-the-middle feature

- modules/llama_cpp_plugin/src/infer_request.cpp
- modules/llama_cpp_plugin/src/plugin.cpp
- modules/llama_cpp_plugin/tests/common/CMakeLists.txt
- modules/llama_cpp_plugin/tests/common/include/llm_inference.hpp
- modules/llama_cpp_plugin/tests/common/src/llm_inference.cpp
- modules/llama_cpp_plugin/tests/functional/src/batching.cpp
- modules/llama_cpp_plugin/tests/functional/src/reset_state.cpp
- modules/llama_cpp_plugin/tests/functional/src/threading.cpp
Passing tensors with batch size > 1 should now be working, with batch indices corresponding to independent prompts and generation sequences. The association of KV-cache entries with individual sequences is done internally inside the `llama.cpp` implementation level.
> [LLAMA_CPP] Enable batch size > 1 

- modules/java_api/src/main/cpp/input_tensor_info.cpp
- modules/java_api/src/main/cpp/jni_common.hpp
- modules/java_api/src/main/cpp/tensor.cpp
- modules/java_api/src/main/java/org/intel/openvino/ElementType.java
Added a hard dependency for data type mapping to avoid errors when the values of [the original enum](https://github.com/openvinotoolkit/openvino/blob/96f6251c21d0c94c18a6128fa185167b6cbcb49b/src/core/include/openvino/core/type/element_type.hpp#L37) are changing.
> [JAVA_API] update for element type passing

- modules/llama_cpp_plugin/notebooks/llama_cpp_plugin_with_qwen.ipynb
- modules/llama_cpp_plugin/notebooks/qwen.ipynb
Adds a notebook that demonstrates the usage of the `LLAMA_CPP` plugin to run LLM inference with the Qwen-1.5-7B-Chat model.
> LLAMA_CPP notebook with Qwen-1.5-7B-Chat

- modules/openvino_code/package-lock.json
- modules/openvino_code/package.json
- modules/openvino_code/shared/model.ts
Moved below models from private hugging face repository to Intel repository
**Phi-2 model new location**: [Intel/phi-2-ov-quantized](https://huggingface.co/Intel/phi-2-ov-quantized)
**Deepseek-coder new location:** [Intel/deepseek-coder-1.3b_base_ov_int8](https://huggingface.co/Intel/deepseek-coder-1.3b_base_ov_int8)
> [OPENVINO_CODE] Move phi-2 and depseek-coder models to Intel repo

- modules/nvidia_plugin/tests/unit/result.cpp
###Details
- Use OpenVINO API to to set tensor descriptor in output for `ParameterStubNode`
- openvinotoolkit/openvino#23713
> [NVIDIA]Fix set tensor descriptor in nvidia tests

- modules/openvino_code/package-lock.json
- modules/openvino_code/package.json
- modules/openvino_code/server/pyproject.toml
CVS-157213-fixing vulnerabilities - [NPM] Fix npm audit findings in ov.contrib 
Ran npm audit fix --force to remove vulnerabilities
Also, updated OV version to 2024.5.0
> CVS-157213-fixing vulnerabilities - [NPM] Fix npm audit findings in ov.contrib 

- modules/java_api/src/main/cpp/jni_common.hpp
- modules/nvidia_plugin/src/cuda_config.hpp
- modules/nvidia_plugin/src/cuda_operation_base.hpp
- modules/nvidia_plugin/src/ops/gather.cpp
- modules/nvidia_plugin/src/ops/scatter_nd_update.cpp
- modules/nvidia_plugin/src/ops/split.cpp
- modules/nvidia_plugin/src/ops/variadic_split.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/ov_finite_comparer.cpp
- modules/nvidia_plugin/tests/unit/memory_manager/cuda_memory_manager_test.cpp
- Use same enum for undefined and dynamic cause compile warning/error in switch cases.
- Repalce undefined with dynamic
- openvinotoolkit/openvino#28766
> Replace undefined type with dynamic

- .github/workflows/code_style.yml
- .github/workflows/linux.yml
- .github/workflows/mac.yml
- .github/workflows/windows.yml
- modules/custom_operations/user_ie_extensions/calculate_grid.cpp
- modules/custom_operations/user_ie_extensions/complex_mul.cpp
- modules/custom_operations/user_ie_extensions/fft.cpp
- modules/custom_operations/user_ie_extensions/grid_sample.cpp
- modules/custom_operations/user_ie_extensions/sparse_conv.cpp
- modules/custom_operations/user_ie_extensions/sparse_conv_transpose.cpp
- modules/java_api/src/test/java/org/intel/openvino/CompiledModelTests.java
- modules/java_api/src/test/java/org/intel/openvino/ModelTests.java
- Update the code to use correct const type in reinterpret cast for const tensors
- Update java test to pass on CI
- openvinotoolkit/openvino#29594
> Update tensor pointer cast

- modules/ollama_openvino/Dockerfile_genai
I wasn't able to build `Dockerfile_genai` until I commented out the proxy lines - went smoothly after that
> Disable proxy lines in Dockerfile_genai

- modules/nvidia_plugin/src/cuda_plugin.cpp
- modules/nvidia_plugin/src/cuda_plugin.hpp
Dependent changes to https://github.com/openvinotoolkit/openvino/pull/31137 for Nvidia plugin
[CVS-166953](https://jira.devtools.intel.com/browse/CVS-166953)
> Add overrides to new plugin methods

- .github/workflows/linux.yml
- .github/workflows/mac.yml
- .github/workflows/windows.yml
Disable the `llama_cpp_plugin` build until #992 is not merged.
> Disable llama_cpp_plugin build

- modules/java_api/src/main/java/org/intel/openvino/Wrapper.java
Resolve these warnings:
```
openvino_contrib/modules/java_api/src/main/java/org/intel/openvino/Wrapper.java:27: warning: [removal] finalize() in Object has been deprecated and marked for removal
protected void finalize() throws Throwable {
^
openvino_contrib/modules/java_api/src/main/java/org/intel/openvino/Wrapper.java:29: warning: [removal] finalize() in Object has been deprecated and marked for removal
super.finalize();
^
2 warnings
```
> [JAVA_API] Replace deprecated .finalize() method usage in Wrapper

- modules/java_api/gradle.properties
- modules/java_api/samples/face_detection_java_sample/build.gradle
- modules/java_api/samples/face_detection_kotlin_sample/build.gradle
- modules/java_api/samples/hello_query_device/build.gradle
- modules/java_api/settings.gradle
- Remove non-existing samples mention in `settings.gradle` and `gradle.properties` to fix samples build
- Replace deprecated (in version 7) and later removed (in version 8) `mainClassName` gradle option with the `application { mainClass = <class_name> }` in the `hello_query_device` and `face_detection samples` so they build with newer Gradle versions
> [JAVA_API] Fix samples build
