- modules/java_api/cpp/infer_request.cpp
fix Java build with Android NDK 20
```
error: cannot
initialize a parameter of type 'JNIEnv **' (aka '_JNIEnv **') with an rvalue of type 'void **'
jvm->AttachCurrentThread((void**)&myNewEnv, &args);
^~~~~~~~~~~~~~~~~
/home/dkurt/Downloads/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/jni.h:1058:39: note: 
passing argument to parameter 'p_env' here
jint AttachCurrentThread(JNIEnv** p_env, void* thr_args)
```
> Fix Android build with Java bindings

- .ci/azure/linux.yml
- .ci/azure/mac.yml
- .ci/azure/windows.yml
- modules/java_api/tests/CMakeLists.txt
- modules/java_api/tests/OpenVinoTestRunner.java
* Linux and Mac Java tests (build only for Windows)
* Also changed new lines from \r\n to \n
> Add Java tests

- modules/java_api/README.md
@likholat @dkurt could you please create more descriptive README.md for Java?
> Removed ENABLE_JAVA from docs

- modules/arm_plugin/src/arm_executable_network.cpp
Should be merged together with https://github.com/openvinotoolkit/openvino/pull/4045
> Removed template parameter in base class

- modules/arm_plugin/README.md
> README.md TYPO

- modules/mo_pytorch/mo_extensions/front/pytorch/batchnorm.py
- modules/mo_pytorch/mo_extensions/front/pytorch/interpolate.py
- modules/mo_pytorch/mo_extensions/front/pytorch/linear.py
- modules/mo_pytorch/test/run_tests.py
> Test detectron2_retinanet

- modules/arm_plugin/tests/functional/shared_tests_instances/skip_tests_config.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/subgraph_tests/constant_result.cpp
Issue: 49256
PR OV: https://github.com/openvinotoolkit/openvino/pull/4120
Links for internal validation in ticket
> Changed ConstantResultSubgraphTest instantiate

- modules/mo_pytorch/test/run_tests.py
StridedSlice was fixed: https://github.com/openvinotoolkit/openvino/pull/4545
> Enable tests with strided slice

- modules/arm_plugin/README.md
- modules/arm_plugin/armplg_build.sh
Updated arm plugin build script source branches to specific release version
> Updated arm plugin build script

- modules/arm_plugin/src/arm_converter/arm_converter_activation.cpp
- modules/arm_plugin/src/opset/ngraph_opset.hpp
A new version of the Gelu operation will be introduced https://github.com/openvinotoolkit/openvino/pull/4497. Need to change ARM plugin to properly use reference implementation.
product-config MR 1444
> Added change to support gelu-7 in reference implementations

- modules/arm_plugin/src/arm_converter/arm_converter_one_hot.cpp
Update arm_converter_one_hot due to revision of OneHot reference implementation (more details could be found in this [PR](https://github.com/openvinotoolkit/openvino/pull/4330))
Ticket: 37522
> OneHot convertor update

- modules/arm_plugin/thirdparty/CMakeLists.txt
IE part https://github.com/openvinotoolkit/openvino/pull/4848/files
> Apple M1 support

- modules/arm_plugin/src/arm_converter/arm_converter.cpp
- modules/arm_plugin/src/arm_converter/arm_converter_normalize_l2.cpp
- modules/arm_plugin/src/opset/normalizel2_arm.cpp
- modules/arm_plugin/src/opset/normalizel2_arm.hpp
- modules/arm_plugin/src/opset/opset.hpp
- modules/arm_plugin/src/transformations/arm_optimizations.cpp
- modules/arm_plugin/src/transformations/convert_normalizel2_arm.cpp
- modules/arm_plugin/src/transformations/convert_normalizel2_arm.hpp
- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/normalize_l2.cpp
Merge after: openvinotoolkit/openvino#4832
> Separate NormalizeL2 op support into native and reference

- .ci/azure/linux.yml
- modules/mo_pytorch/test/requirements.txt
Use the smallest `requirements_*.txt` from MO
> Remove MO deps from mo_pytorch module

- .ci/azure/mac.yml
resolves https://github.com/openvinotoolkit/openvino_contrib/issues/95
> Run Java tests on Mac through Gradle

- modules/arm_plugin/src/arm_converter/arm_converter.cpp
- modules/arm_plugin/src/arm_converter/arm_converter_gather.cpp
Relates to openvinotoolkit/openvino#4885
> Switch Gather to v1

- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/batch_to_space.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/convolution_backprop_data.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/psroi_pooling.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/reduce_ops.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/region_yolo.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/reorg_yolo.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/roi_align.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/space_to_batch.cpp
Merge after  openvinotoolkit/openvino#4936
> Added FP16 test cases

- modules/arm_plugin/src/arm_converter/arm_converter.cpp
- modules/arm_plugin/src/arm_converter/arm_converter_transpose.cpp
- modules/arm_plugin/src/opset/opset.hpp
- modules/arm_plugin/src/opset/transpose_arm.cpp
- modules/arm_plugin/src/opset/transpose_arm.hpp
- modules/arm_plugin/src/transformations/arm_optimizations.cpp
- modules/arm_plugin/src/transformations/convert_transpose_arm.cpp
- modules/arm_plugin/src/transformations/convert_transpose_arm.hpp
- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/transpose.cpp
Merge after openvinotoolkit/openvino#4688
> Separate Transpose layer support into native and reference

- modules/arm_plugin/src/arm_config.cpp
- modules/arm_plugin/src/arm_config.hpp
- modules/arm_plugin/src/arm_executable_network.cpp
- modules/arm_plugin/src/arm_executable_network.hpp
- modules/arm_plugin/src/arm_plugin.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/skip_tests_config.cpp
* Also Disable thread binding option as it has no sense for performance for current base sequential threading used for arm plugin.
> Fixed multithreaded plugin load

- modules/arm_plugin/src/arm_executable_network.cpp
- modules/arm_plugin/src/arm_executable_network.hpp
- modules/arm_plugin/src/arm_infer_request.cpp
- modules/arm_plugin/src/arm_infer_request.hpp
- modules/arm_plugin/src/arm_plugin.cpp
Base PR: https://github.com/openvinotoolkit/openvino/pull/5125
> Refactored internal internal infer request

- modules/arm_plugin/tests/functional/conformance/skip_configs/skip_config_arm.lst
> [IE TESTS] Add skip test config file for Conformance suite

- modules/arm_plugin/src/arm_converter/arm_converter.cpp
- modules/arm_plugin/src/arm_converter/arm_converter_gather.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/gather.cpp
Depends on [OpenVINO PR#5373](https://github.com/openvinotoolkit/openvino/pull/5373)
Test could be extended to negative batch index since implemented in reference
> Added support for opset7::Gather

- modules/mo_pytorch/mo_pytorch.py
> [MO] add default value for ie_is_available

- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/interpolation.cpp
Changing tests due to modifications in openvino
https://github.com/openvinotoolkit/openvino/pull/5520
Ticket -51846
> Interpolation tests changed

- modules/arm_plugin/src/arm_executable_network.hpp
- modules/arm_plugin/src/arm_plugin.cpp
- modules/arm_plugin/src/arm_plugin.hpp
Based on https://github.com/openvinotoolkit/openvino/pull/4923
> Merged plugin and exec network internal implementation

- modules/java_api/org/intel/openvino/IECore.java
> [Java] fix Klocwork

- modules/arm_plugin/src/arm_config.cpp
- modules/arm_plugin/src/arm_config.hpp
- modules/arm_plugin/src/arm_plugin.cpp
- modules/arm_plugin/src/transformations/arm_optimizations.cpp
- modules/arm_plugin/src/transformations/arm_optimizations.hpp
* Add configuration Key that enables intermediate topology dump as `.dot` file
> Graph dump configuration key

- modules/arm_plugin/src/arm_converter/arm_converter.cpp
- modules/arm_plugin/src/arm_converter/arm_converter.hpp
- modules/arm_plugin/src/arm_converter/arm_converter_split.cpp
- modules/arm_plugin/src/opset/opset.hpp
- modules/arm_plugin/src/opset/split_arm.cpp
- modules/arm_plugin/src/opset/split_arm.hpp
- modules/arm_plugin/src/transformations/arm_optimizations.cpp
- modules/arm_plugin/src/transformations/arm_optimizations.hpp
- modules/arm_plugin/src/transformations/convert_split.cpp
- modules/arm_plugin/src/transformations/convert_split.hpp
- modules/arm_plugin/src/transformations/quantize_fusion.cpp
- modules/arm_plugin/src/transformations/quantize_fusion.hpp
- modules/arm_plugin/tests/functional/shared_tests_instances/low_precision_transformations/arm_convolution.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/low_precision_transformations/arm_convolution_branch.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/low_precision_transformations/arm_group_convolution.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/low_precision_transformations/convolution_transformation.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/low_precision_transformations/group_convolution_transformation.cpp
* New LP tests
* Fix outputs counting for `amr_compute::MemoryManger` in case of ArmNoOP on output
* Fixed QuantizationInfo storing in ArmQuantize creation pass
> New lp tests

- modules/arm_plugin/src/arm_converter/arm_converter_nms.cpp
See https://github.com/openvinotoolkit/openvino/pull/6446
> Removed tensor name

- modules/arm_plugin/src/CMakeLists.txt
Related to https://github.com/openvinotoolkit/openvino/pull/6422
> Use COMPILE_OPTIONS instead of COMPILE_FLAGS

- modules/arm_plugin/src/arm_converter/arm_converter_fake_quantize.cpp
- switch to new reference implementation to get broadcast attribute
- 60607
> switch to new reference implementation in FakeQuantize

- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/mvn.cpp
OV MVN1 SLT is changed, arm plugin has to be aligned with new API.
> Align mvn SLTs with MVN1 api.

- modules/arm_plugin/src/opset/utils.hpp
This PR is connected with these changes: https://github.com/openvinotoolkit/openvino/pull/6920
> Introduce define to change namespaces

- modules/arm_plugin/src/arm_executable_network.cpp
- modules/arm_plugin/src/arm_executable_network.hpp
based on https://github.com/openvinotoolkit/openvino/pull/7189
> Changed internal GetExecGraph API

- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/convert.cpp
- Update convert tests to use conversion SLT class 
- 63217
> Update convert tests to use conversion SLT class

- modules/arm_plugin/docs/arm_opset.md
Updated documentation in accordance with PR #150
> Marked DFT and IDFT layers as supported by ArmPlugin

- .ci/azure/linux.yml
- .ci/azure/windows.yml
- modules/mo_pytorch/README.md
- modules/mo_pytorch/mo_extensions/load/pytorch/hooks.py
related: https://github.com/openvinotoolkit/openvino/pull/6255
> Replace Python assert to exception

- modules/arm_plugin/src/arm_executable_network.cpp
- modules/arm_plugin/src/arm_executable_network.hpp
- modules/arm_plugin/src/arm_infer_request.cpp
- modules/arm_plugin/src/arm_infer_request.hpp
ArmInferRequest creation process updated to address changes introduced by OpenVINO PR#7962
> ArmInferRequest creation process updated

- modules/arm_plugin/src/arm_executable_network.cpp
- modules/arm_plugin/src/arm_executable_network.hpp
- modules/arm_plugin/src/arm_infer_request.cpp
- modules/arm_plugin/src/arm_infer_request.hpp
Reverts openvinotoolkit/openvino_contrib#228
> Revert "ArmInferRequest creation process updated"

- modules/arm_plugin/src/arm_plugin.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_executable_network/core_integration.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_executable_network/exec_network_base.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/callback.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/inference_chaining.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/io_tensor.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/multithreading.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/perf_counters.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/wait.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_plugin/core_integration.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/skip_tests_config.cpp
Waiting for https://github.com/openvinotoolkit/openvino/pull/8710
> Added openvino beh tests

- modules/arm_plugin/tests/functional/shared_tests_instances/low_precision_transformations/group_convolution_transformation.cpp
main PR: https://github.com/openvinotoolkit/openvino/pull/8678
product-config: https://github.com/openvinotoolkit/openvino/pull/8678
> [LPT] GroupConvolution: 3D tensor support

- .ci/azure/linux.yml
- .ci/azure/windows.yml
- modules/arm_plugin/src/CMakeLists.txt
- modules/arm_plugin/src/arm_converter/arm_converter.hpp
Depends on https://github.com/openvinotoolkit/openvino/pull/8570
> Fixed pp header

- modules/arm_plugin/src/opset/utils.hpp
based on https://github.com/openvinotoolkit/openvino/pull/8288
> Added ov::Any

- modules/arm_plugin/src/arm_converter/arm_converter.cpp
- modules/arm_plugin/src/arm_converter/arm_converter_conv.cpp
- modules/arm_plugin/src/arm_infer_request.cpp
- modules/arm_plugin/src/opset/utils.hpp
- modules/arm_plugin/src/transformations/arm_optimizations.cpp
- modules/arm_plugin/src/transformations/quantize_fusion.cpp
- modules/arm_plugin/src/transformations/store_result_name.cpp
- Based on https://github.com/openvinotoolkit/openvino/pull/8520
> Variant replaced with Runtime Attribute

- .ci/azure/linux.yml
related: https://github.com/openvinotoolkit/openvino/pull/8820
> Install MO by wheel

- modules/mo_pytorch/README.md
- modules/mo_pytorch/mo_extensions/front/pytorch/detection_output_ext.py
- modules/mo_pytorch/mo_extensions/front/pytorch/elementwise_ext.py
- modules/mo_pytorch/mo_extensions/front/pytorch/flatten_ext.py
- modules/mo_pytorch/mo_extensions/front/pytorch/roi_align_ext.py
- modules/mo_pytorch/mo_extensions/front/pytorch/topk_ext.py
- modules/mo_pytorch/mo_extensions/load/pytorch/hooks.py
- modules/mo_pytorch/mo_extensions/load/pytorch/loader.py
- modules/mo_pytorch/mo_extensions/load/pytorch/mask_rcnn/mask_rcnn.py
- modules/mo_pytorch/mo_extensions/load/pytorch/model_hooks.py
- modules/mo_pytorch/test/run_tests.py
https://pytorch.org/vision/master/_modules/torchvision/models/detection/mask_rcnn.html
* For better efficiency, use `box_detections_per_img` option to limit maximum number of detected objects and `rpn_post_nms_top_n_test` to limit RPN's number of proposals.
> [PyTorch] Mask R-CNN from Torchvision

- .ci/azure/linux.yml
- .ci/azure/windows.yml
related: https://github.com/openvinotoolkit/openvino/pull/9072
> OpenVINO moved temp folder

- modules/arm_plugin/docs/arm_opset.md
- modules/arm_plugin/src/arm_converter/arm_converter.cpp
- modules/arm_plugin/src/arm_converter/arm_converter_convert_color_i420.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/convert_color_i420.cpp
fixed strides calculations in nv12
> [ARM Plugin] added color_convert_i420 reference support

- modules/arm_plugin/src/transformations/arm_optimizations.cpp
> [arm_plugin] remove algebraic_simplification pass because it do nothing

- modules/mo_pytorch/mo_pytorch.py
Removed in https://github.com/openvinotoolkit/openvino/pull/9681
> Remove check_python_version

- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_executable_network/exec_network_base.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/callback.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/inference_chaining.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/io_tensor.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/multithreading.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/perf_counters.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/wait.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_plugin/core_integration.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/eltwise.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/softmax.cpp
based on https://github.com/openvinotoolkit/openvino/pull/7750
> Used any to pass config values

- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_executable_network/exec_network_base.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/callback.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/inference_chaining.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/io_tensor.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/multithreading.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/perf_counters.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/wait.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_plugin/core_integration.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/eltwise.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/softmax.cpp
Reverts openvinotoolkit/openvino_contrib#262
> Revert "Used any to pass config values"

- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_executable_network/exec_network_base.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/callback.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/inference_chaining.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/io_tensor.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/multithreading.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/perf_counters.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/wait.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_plugin/core_integration.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/eltwise.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/softmax.cpp
Reverts openvinotoolkit/openvino_contrib#288
> Revert "Used any to pass config values (#262)"

- .ci/azure/android_arm64.yml
- .ci/azure/linux_arm64.yml
related: https://github.com/openvinotoolkit/openvino/pull/9827
> [CI] Rename ENABLE_VPU to ENABLE_MYRIAD

- modules/arm_plugin/src/arm_config.cpp
- modules/arm_plugin/src/arm_executable_network.cpp
- modules/arm_plugin/src/arm_plugin.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_executable_network/exec_network_base.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/callback.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/inference_chaining.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/io_tensor.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/multithreading.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/ov_infer_request/wait.cpp
* based on https://github.com/openvinotoolkit/openvino_contrib/pull/262
> Used OV2.0 configuration API

- modules/arm_plugin/tests/functional/shared_tests_instances/behavior/plugin/set_preprocess.cpp
[OpenVINO PR](https://github.com/openvinotoolkit/openvino/pull/10328)
> [IE TESTS] Move preprocess tests under behavior/plugin

- modules/optimum/tests/openvino/requirements.txt
@likholat, thanks for review of https://github.com/openvinotoolkit/openvino_contrib/pull/331 but there are remaining alerts that can be solved only by TensorFlow 2.8.0:
https://github.com/openvinotoolkit/openvino_contrib/security/dependabot/59
https://github.com/openvinotoolkit/openvino_contrib/security/dependabot/58
please review this PR
resolves https://github.com/dkurt/optimum-openvino/issues/9
> Use TensorFlow 2.8.0 (dependabot alert)

- modules/arm_plugin/src/arm_converter/arm_converter.cpp
- modules/arm_plugin/src/arm_converter/arm_converter_pool.cpp
- modules/arm_plugin/src/transformations/arm_optimizations.cpp
- modules/arm_plugin/src/transformations/convert_maxpool_v8.cpp
- modules/arm_plugin/src/transformations/convert_maxpool_v8.hpp
- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/pooling.cpp
Propagation of https://github.com/openvinotoolkit/openvino_contrib/pull/311
> [ARM Plugin] maxpool-v8 transformation (#311)

- modules/arm_plugin/README.md
- modules/arm_plugin/src/transformations/quantize_fusion.cpp
- modules/mo_pytorch/mo_pytorch.py
- modules/mo_pytorch/samples/mask_rcnn.py
- modules/mo_pytorch/test/run_tests.py
Propagation of https://github.com/openvinotoolkit/openvino_contrib/pull/328
* Added fusing of quantization prescaling multiplication to convolution layer
* Inlined negation folding for quantization prescaling fusion
* Updated README with I8 support
> Added fusing of quantization multiplication to convolution layer (#328)

- modules/java_api/tests/CoreTests.java
- modules/java_api/tests/compatibility/IECoreTests.java
https://github.com/openvinotoolkit/openvino_contrib/issues/350#event-6289159371
> [JAVA] Fixed exception message in tests

- modules/optimum/optimum/intel/openvino/modeling_ov_utils.py
partially revert https://github.com/openvinotoolkit/openvino_contrib/pull/367
> [Optimum] Restore MO conversion for TensorFlow models using subprocess

- modules/arm_plugin/src/arm_executable_network.cpp
- modules/arm_plugin/src/arm_plugin.cpp
> Fixed segfault in Executor Manager

- .ci/azure/linux_cuda.yml
- .github/workflows/history_cuda.yml
- .github/workflows/sanitizer_cuda.yml
- .github/workflows/test_cuda.yml
> [NVIDIA] Update cuda ci after renaming

- modules/java_api/build.gradle
- modules/java_api/cpp/any.cpp
- modules/java_api/cpp/core.cpp
- modules/java_api/cpp/infer_request.cpp
- modules/java_api/cpp/model.cpp
- modules/java_api/cpp/openvino_java.hpp
- modules/java_api/org/intel/openvino/Any.java
- modules/java_api/org/intel/openvino/Core.java
- modules/java_api/org/intel/openvino/InferRequest.java
- modules/java_api/org/intel/openvino/Model.java
- modules/java_api/settings.gradle
- modules/java_api/tests/CoreTests.java
- modules/java_api/tests/ModelTests.java
Resolved conflicts for https://github.com/openvinotoolkit/openvino_contrib/pull/364
> More java api 2.0

- modules/arm_plugin/dockerfiles/Dockerfile.RPi32_buster
- modules/arm_plugin/dockerfiles/Dockerfile.RPi32_stretch
- modules/arm_plugin/dockerfiles/Dockerfile.RPi64_bionic
- modules/arm_plugin/dockerfiles/Dockerfile.RPi64_focal
- modules/arm_plugin/scripts/arm_cpu_plugin_build.sh
- modules/arm_plugin/thirdparty/CMakeLists.txt
- Also, added proper wheels support
> Updated OpenVINO ARM build inside the docker images

- modules/arm_plugin/tests/functional/shared_tests_instances/set_device_name.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/set_device_name.cpp
Connected with OpenVINO PR: https://github.com/openvinotoolkit/openvino/pull/13339/files
> [IE TESTS] Add device suffix

- modules/arm_plugin/src/transformations/arm_optimizations.cpp
Changes required for cross merging with [OV PR #13172](https://github.com/openvinotoolkit/openvino/pull/13172)
> LPT: changed PrecisionsRestriction creation

- .gitignore
- modules/arm_plugin/src/arm_plugin.cpp
- modules/arm_plugin/src/transformations/arm_optimizations.cpp
- modules/arm_plugin/src/transformations/conv_bias_fusion.cpp
- modules/arm_plugin/src/transformations/finalize_trailing_nodes.cpp
- modules/arm_plugin/src/transformations/quantize_fusion.cpp
- modules/arm_plugin/src/transformations/store_result_name.cpp
- modules/nvidia_plugin/src/cuda_executable_network.cpp
- modules/nvidia_plugin/src/cuda_plugin.cpp
- modules/nvidia_plugin/src/ops/result.cpp
- modules/nvidia_plugin/src/transformer/bidirectional_lstm_sequence_composition.cpp
- modules/nvidia_plugin/src/transformer/cuda_graph_transformer.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/mvn.cpp
- modules/nvidia_plugin/tests/functional/transformations/cuda_transformations_test.cpp
Since OpenVINO Transformations remove its dependencies to nGraph updates are needed here as well.
OV PRs depending on this one
https://github.com/openvinotoolkit/openvino/pull/13653
https://github.com/openvinotoolkit/openvino/pull/13558
> Transformations transition to ov namespace

- modules/arm_plugin/src/arm_converter/arm_converter.cpp
- modules/arm_plugin/src/arm_converter/arm_converter.hpp
- modules/arm_plugin/src/arm_converter/arm_converter_convert.cpp
- modules/arm_plugin/src/arm_converter/arm_converter_convert_like.cpp
- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/convert.cpp
should be merged after https://github.com/openvinotoolkit/openvino/pull/14475
> [ARM CPU plugin] FP64 support

- modules/nvidia_plugin/src/transformer/cuda_graph_transformer.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/activation.cpp
- *Enable PRelu with slope rank 1*
- *ticket-id*
Should be merged after PR https://github.com/openvinotoolkit/openvino/pull/14169
> [NVIDIA] Enable unsupported PRelu case

- modules/nvidia_plugin/tests/functional/skip_tests_config.cpp
> [NVIDIA] Disable caching support tests

- modules/nvidia_plugin/src/transformer/cuda_graph_transformer.cpp
- *Currently NVIDIA executes Converts for compressed only IR format even GPU supports half precision. This PR fixes this behavior.*
- *TODO: support inference precision property when new API config will be added*
-
[nvidia_log_after_fix.txt](https://github.com/openvinotoolkit/openvino_contrib/files/10207480/nvidia_log_after_fix.txt)
[nvidia_log_before.txt](https://github.com/openvinotoolkit/openvino_contrib/files/10207483/nvidia_log_before.txt)
> [NVIDIA] Handle compressed only format correctly

- modules/nvidia_plugin/src/transformer/cuda_graph_transformer.cpp
- modules/nvidia_plugin/src/transformer/fuse_conv_biasadd_activation.cpp
- modules/nvidia_plugin/src/transformer/fuse_conv_biasadd_activation.hpp
- modules/nvidia_plugin/src/transformer/rt_info/cuda_node_id.cpp
- modules/nvidia_plugin/src/transformer/rt_info/cuda_node_id.hpp
- modules/nvidia_plugin/tests/unit/CMakeLists.txt
- modules/nvidia_plugin/tests/unit/transformations/fuse_conv_biasadd_activation.cpp
- *Fix case when `Add` has `FusedConvolution` on both inputs which lead to hangs in mobilenet\* topologies*
- *Add transformation unit tests*
> [NVIDIA] Fix convolution fusion

- .github/workflows/history_cuda.yml
fixing git command lines to remove hardcoded paths
> 'History CUDA' workflow update with github runner specific

- modules/arm_plugin/src/opset/CMakeLists.txt
- modules/arm_plugin/src/transformations/CMakeLists.txt
Ported [fix](https://github.com/openvinotoolkit/openvino_contrib/pull/540) to release branch
> Fixed arm plugin compilation with OpenVINO static (#540)

- modules/arm_plugin/src/arm_converter/arm_converter_depth_to_space.cpp
There is a need to support cases that are not supported by ACL for `single-image-super-resolution-1032`
Reference ticket: CVS-101339
> DepthToSpace ref implementation

- modules/nvidia_plugin/tests/functional/skip_tests_config.cpp
Tickets:
- *101751*
- *101746*
- *101747*
- *101748*
- *101755*
> [NVIDIA] Add dynamic tests to skip config

- modules/arm_plugin/src/arm_converter/arm_converter.hpp
- modules/arm_plugin/src/arm_converter/arm_converter_concat.cpp
- modules/arm_plugin/src/arm_converter/arm_converter_convert.cpp
Propagation of https://github.com/openvinotoolkit/openvino_contrib/pull/551
> [ARM plugin] U64 and bfloat16 support for reference ops 

- modules/arm_plugin/src/arm_plugin.cpp
Propagation of https://github.com/openvinotoolkit/openvino_contrib/pull/566
> [ARM Plugin] Raise user friendly error that dynamic shapes are not supported

- modules/arm_plugin/src/arm_converter/arm_converter.hpp
Fix for Android build: https://dev.azure.com/openvinoci/dldt/_build/results?buildId=477562&view=logs&j=92ba3447-fcaa-530d-6438-b829fe1e7d1d&t=b0a91e75-8666-5718-e63e-df215ecb48f9&l=5129
Issue was introduced by: https://github.com/openvinotoolkit/openvino_contrib/pull/568
> [ARM CPU plugin] Delete unused variables in MakeArgument

- modules/java_api/README.md
resolves https://github.com/openvinotoolkit/openvino_contrib/issues/454
@ilya-lavrenov, trigger for builds on PRs would be nice
> Replace link to Java docs

- .ci/azure/linux.yml
- .ci/azure/windows.yml
- README.md
- modules/custom_operations/CMakeLists.txt
- modules/custom_operations/README.md
- modules/custom_operations/examples/calculate_grid/calculate_grid.py
- modules/custom_operations/examples/calculate_grid/export_model.py
- modules/custom_operations/examples/complex_mul/complex_mul.py
- modules/custom_operations/examples/complex_mul/export_model.py
- modules/custom_operations/examples/fft/export_model.py
- modules/custom_operations/examples/fft/fft.py
- modules/custom_operations/examples/sparse_conv/export_model.py
- modules/custom_operations/examples/sparse_conv/sparse_conv.py
- modules/custom_operations/tests/requirements.txt
- modules/custom_operations/tests/run_tests.py
- modules/custom_operations/user_ie_extensions/CMakeLists.txt
- modules/custom_operations/user_ie_extensions/calculate_grid.cpp
- modules/custom_operations/user_ie_extensions/calculate_grid.hpp
- modules/custom_operations/user_ie_extensions/complex_mul.cpp
- modules/custom_operations/user_ie_extensions/complex_mul.hpp
- modules/custom_operations/user_ie_extensions/fft.cpp
- modules/custom_operations/user_ie_extensions/fft.hpp
- modules/custom_operations/user_ie_extensions/grid_sample.cpp
- modules/custom_operations/user_ie_extensions/grid_sample.hpp
- modules/custom_operations/user_ie_extensions/ov_extension.cpp
- modules/custom_operations/user_ie_extensions/sparse_conv.cpp
- modules/custom_operations/user_ie_extensions/sparse_conv.hpp
- modules/custom_operations/user_ie_extensions/sparse_conv_transpose.cpp
- modules/custom_operations/user_ie_extensions/sparse_conv_transpose.hpp
- third-party-programs.txt
This module:
1. is a tutorial of how to support custom CPU operations, unsupported by OpenVINO (how to create OpenVINO CPU extensions)
2. includes some custom layers that are still required for open source projects that use OpenVINO (see the list in the README)
> OpenVINO CPU extensions: custom operations support

- modules/arm_plugin/src/arm_config.cpp
Details:
add enable_profiling & PERFORMANCE_HINT parameter checking;
Tickets:
98110
> [ARM Plugin] add enable_profiling & PERFORMANCE_HINT parameter checking

- .ci/azure/linux.yml
- modules/custom_operations/tests/requirements.txt
PR to address https://github.com/openvinotoolkit/openvino_contrib/security/dependabot/96
> Updated requirements.txt file to avoid vulnerability

- modules/arm_plugin/src/CMakeLists.txt
- modules/arm_plugin/src/opset/CMakeLists.txt
- modules/arm_plugin/src/transformations/CMakeLists.txt
- modules/arm_plugin/tests/functional/CMakeLists.txt
- modules/arm_plugin/thirdparty/CMakeLists.txt
See 
https://github.com/ARM-software/ComputeLibrary/blob/1b3192e8a23513031163dc14d248f47671986121/SConscript#L655-L660
> Remove usage of legacy arm_compute_core-static

- modules/nvidia_plugin/src/cuda_infer_request.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/behavior/executable_network/get_metric.cpp
- modules/nvidia_plugin/tests/functional/skip_tests_config.cpp
**Details:**
- *Fix for https://github.com/openvinotoolkit/openvino/pull/15387*
- *Disable tests for https://github.com/openvinotoolkit/openvino/pull/14754*
> [NVIDIA] fix tests for latest master

- modules/arm_plugin/tests/functional/shared_tests_instances/single_layer_tests/select.cpp
- modules/nvidia_plugin/src/ops/cudnn_tensor_op_base.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/select.cpp
Fix issue caused by https://github.com/openvinotoolkit/openvino/pull/15806
> [Remove APIs] fix error

- modules/arm_plugin/tests/functional/shared_tests_instances/skip_tests_config.cpp
> Skip test canStartSeveralAsyncInsideCompletionCallbackWithSafeDtor for MULTI

- modules/nvidia_plugin/CMakeLists.txt
- modules/nvidia_plugin/README.md
- modules/nvidia_plugin/src/CMakeLists.txt
- modules/nvidia_plugin/src/cuda/math.cuh
- modules/nvidia_plugin/src/kernels/power.cu
- modules/nvidia_plugin/tests/unit/CMakeLists.txt
- *added `CMAKE_CUDA_ARCHITECTURES` support and new architectures*
- 102638
> [NVIDIA] CMAKE_CUDA_ARCHITECTURES support and new architectures

- modules/arm_plugin/src/transformations/finalize_trailing_nodes.cpp
- modules/arm_plugin/src/transformations/finalize_trailing_nodes.hpp
- modules/arm_plugin/src/transformations/store_result_name.cpp
- modules/arm_plugin/src/transformations/store_result_name.hpp
- modules/nvidia_plugin/src/cuda_executable_network.cpp
- modules/nvidia_plugin/tests/functional/transformations/cuda_transformations_test.cpp
Remove call run_on_function(), replaced by run_on_model()
> [Remove APIs] fix issue in arm plugin caused by deprecated run_on_function()

- modules/nvidia_plugin/README.md
To align with core openvino. Once approved - Jenkins validation will be switched to Ubuntu 20 as well
> [NVIDIA] Update supported OS in docs

- modules/arm_plugin/tests/functional/shared_tests_instances/skip_tests_config.cpp
> disable get config test for multi/auto plugin

- modules/nvidia_plugin/src/CMakeLists.txt
- modules/nvidia_plugin/src/cuda_plugin.cpp
- *Fix GetMetric/GetConfig for different device ids*
> [NVIDIA] Fix GetMetric/GetConfig for different device ids

- modules/nvidia_plugin/src/cuda/math.cuh
- modules/nvidia_plugin/tests/unit/CMakeLists.txt
- modules/nvidia_plugin/tests/unit/convert_benchmark.cpp
- *add some fixes for build on Windows*
- 107838
- 107928
> Windows Build Fixes

- modules/nvidia_plugin/include/nvidia/properties.hpp
- modules/nvidia_plugin/src/cuda_config.cpp
- modules/nvidia_plugin/src/cuda_config.hpp
- modules/nvidia_plugin/src/cuda_executable_network.cpp
- modules/nvidia_plugin/src/cuda_executable_network.hpp
- modules/nvidia_plugin/src/cuda_graph.cpp
- modules/nvidia_plugin/src/cuda_graph.hpp
- modules/nvidia_plugin/src/cuda_infer_request.cpp
- modules/nvidia_plugin/src/cuda_infer_request.hpp
- modules/nvidia_plugin/src/cuda_inference_request_context.hpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/activation_slt.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/gather.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/lstm_cell.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/range.cpp
- modules/nvidia_plugin/tests/unit/concat.cpp
- modules/nvidia_plugin/tests/unit/convert_benchmark.cpp
- modules/nvidia_plugin/tests/unit/limits.cpp
- modules/nvidia_plugin/tests/unit/logical_not_benchmark.cpp
- modules/nvidia_plugin/tests/unit/parameter.cpp
- modules/nvidia_plugin/tests/unit/pooling_tests.cpp
- modules/nvidia_plugin/tests/unit/relu.cpp
- modules/nvidia_plugin/tests/unit/result.cpp
- modules/nvidia_plugin/tests/unit/select_benchmark.cpp
- modules/nvidia_plugin/tests/unit/sigmoid_benchmark.cpp
- modules/nvidia_plugin/tests/unit/strided_slice_benchmark.cpp
- *Add 'USE_CUDA_GRAPH' Configuration Option for future use with Cuda Graphs*
- 107838
> Add 'USE_CUDA_GRAPH' Configuration Option

- modules/nvidia_plugin/tests/functional/skip_tests_config.cpp
- *Revert disabling some tests due to cuda version update* https://github.com/openvinotoolkit/openvino_contrib/pull/577
- 101753
> [NVIDIA] Revert disabling some tests due to cuda version update

- modules/nvidia_plugin/Dockerfile
- modules/nvidia_plugin/README.md
- *Update version of cuda packages in README file according to CI environment..*
- *Update cuda packages in docker image*
Original PR for docker image update: https://github.com/openvinotoolkit/openvino_contrib/pull/530
- 109616
> [NVIDIA] CUDA version update

- modules/nvidia_plugin/README.md
- modules/nvidia_plugin/build.sh
- modules/nvidia_plugin/docker.sh
- modules/nvidia_plugin/wheel/openvino_nvidia/__init__.py
- modules/nvidia_plugin/wheel/requirements-dev.txt
- modules/nvidia_plugin/wheel/requirements.txt
- modules/nvidia_plugin/wheel/setup.py
- *Fix bandit warnings*
- *Update OpenVINO version from 2022.1.0 to 2022.3.0 in setup*
- 109494
> [NVIDIA] Fix bandit warnings, update release tags

- modules/nvidia_plugin/src/CMakeLists.txt
**Please do not merge without approve!**
> [NVIDIA] Enable CPack artifacts

- modules/nvidia_plugin/src/cuda_config.cpp
- modules/nvidia_plugin/src/cuda_config.hpp
- modules/nvidia_plugin/src/cuda_plugin.cpp
- *Support internal properties*
- *Handle config device id*
Connected PR https://github.com/openvinotoolkit/openvino/pull/17820
- *ticket-id*
> [NVIDIA] Support internal properties. Handle config device id

- modules/nvidia_plugin/src/cuda_infer_request.cpp
- modules/nvidia_plugin/src/cuda_infer_request.hpp
- modules/nvidia_plugin/src/cuda_plugin.cpp
- modules/nvidia_plugin/src/cuda_plugin.hpp
Depends on: https://github.com/openvinotoolkit/openvino/pull/18441
> Changed API in NVIDIA plugin

- .ci/azure/linux_cuda.yml
- .github/workflows/sanitizer_cuda.yml
- .github/workflows/test_cuda.yml
- modules/nvidia_plugin/build.sh
- modules/nvidia_plugin/tests/functional/CMakeLists.txt
- modules/nvidia_plugin/tests/unit/CMakeLists.txt
- modules/nvidia_plugin/utils/lsan-suppressions.txt
- modules/nvidia_plugin/utils/pre-push-impl.sh
- *Rename test binaries: CudaFuncTests  -> ov_nvidia_func_tests , CudaUnitTests -> ov_nvidia_unit_tests*
- *ticket-id*
> [NVIDIA] Rename test binaries

- modules/java_api/src/test/java/org/intel/openvino/CoreTests.java
- modules/java_api/src/test/java/org/intel/openvino/OVTest.java
Closes https://github.com/openvinotoolkit/openvino_contrib/issues/628
> [JAVA API] read_model for onnx test

- modules/nvidia_plugin/src/cuda_compiled_model.cpp
- modules/nvidia_plugin/src/cuda_config.cpp
- modules/nvidia_plugin/src/cuda_config.hpp
- modules/nvidia_plugin/tests/unit/executable_network.cpp
- *Support ov::internal::exclusive_async_requests property (align behaviour with CPU and GPU*
Connected PR https://github.com/openvinotoolkit/openvino/pull/18746/
> [NVIDIA] Support ov::internal::exclusive_async_requests property

- modules/nvidia_plugin/src/kernels/gather.cu
- modules/nvidia_plugin/src/kernels/gather.hpp
- modules/nvidia_plugin/src/ops/gather.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/gather.cpp
- *Fix Gather behavior with out of range indices to be consistent with Gather v8 requirements, i.e. write zeros for out of range indices*
- 116466
> [NVIDIA] Fix Gather behavior with out of range indices to be consistent with Gather v8 requirements

- modules/nvidia_plugin/tests/functional/shared_tests_instances/behavior/infer_request/infer_request.cpp
Removes unused header file inclusion.
> [NVIDIA] Remove unused include

- modules/nvidia_plugin/tests/unit/transformations/cuda_transformations_test.cpp
- modules/nvidia_plugin/tests/unit/transformations/fuse_conv_biasadd_activation.cpp
Rename function to model.
Related to https://github.com/openvinotoolkit/openvino/pull/19366
> Transformation tests API 2.0 transition

- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/fully_connected.cpp
- *Fix test after PR https://github.com/openvinotoolkit/openvino_contrib/pull/700/*
> [NVIDIA] Fix MatMul test

- modules/nvidia_plugin/tests/unit/transformations/concat_transformation.cpp
- modules/nvidia_plugin/tests/unit/transformations/cuda_transformations_test.cpp
- modules/nvidia_plugin/tests/unit/transformations/fuse_conv_biasadd_activation.cpp
- modules/nvidia_plugin/tests/unit/transformations/fuse_matmul_add.cpp
- modules/nvidia_plugin/tests/unit/transformations/remove_redundant_convert_transformation.cpp
API 2.0 transition: ngraph to ov renaming
Related to https://github.com/openvinotoolkit/openvino/pull/19475
Ticket:
CVS-111373
> Rename test_utils file

- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/logical_test.cpp
- *Move Logical layer test to API 2.0*
Depends on https://github.com/openvinotoolkit/openvino/pull/20196
- *111380*
> [NVIDIA] Move Logical layer test to API 2.0

- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/eltwise_test.cpp
Ticket: [CVS-125461](https://jira.devtools.intel.com/browse/CVS-125461)
> Disable `smoke_FloorMod` on `u` types

- modules/nvidia_plugin/src/memory_manager/model/cuda_memory_model_builder.cpp
- modules/nvidia_plugin/src/memory_manager/model/cuda_memory_model_builder.hpp
The [PR](https://github.com/openvinotoolkit/openvino/pull/19644) to OpenVINO repo
> [NVIDIA] Moved MemorySolver to API 2.0

- modules/nvidia_plugin/src/transformer/nodes/fused_convolution_backprop_data.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/convolution_backprop_data.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/convolution_backprop_data_add.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/convolution_biasadd_activation.hpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/fully_connected.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/gru_cell.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/gru_sequence.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/lstm_cell.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/lstm_sequence.cpp
- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/topk.cpp
- modules/nvidia_plugin/tests/unit/cuda_multi_graph_test.cpp
Unblock https://github.com/openvinotoolkit/openvino/pull/21416
> `ngraph::opset` -> `ov::opset`

- .ci/azure/linux.yml
- modules/custom_operations/pyproject.toml
- modules/custom_operations/user_ie_extensions/tokenizer/python/openvino_tokenizers/constants.py
- modules/custom_operations/user_ie_extensions/tokenizer/python/openvino_tokenizers/convert_tokenizer.py
- modules/custom_operations/user_ie_extensions/tokenizer/python/openvino_tokenizers/hf_parser.py
- modules/custom_operations/user_ie_extensions/tokenizer/python/openvino_tokenizers/tiktoken_parser.py
- modules/custom_operations/user_ie_extensions/tokenizer/python/openvino_tokenizers/tokenizer_pipeline.py
- modules/custom_operations/user_ie_extensions/tokenizer/python/tests/pass_rates.json
- modules/custom_operations/user_ie_extensions/tokenizer/python/tests/tokenizers_test.py
Add Bandit check to Linux CI
Refactor Decoder to Detokenizer leftovers
> [Tokenizers] Add Bandit Check

- modules/custom_operations/LICENSE
- modules/custom_operations/SECURITY.md
- modules/custom_operations/pyproject.toml
- modules/custom_operations/readme.txt
- modules/custom_operations/third-party-programs.txt
Add separate LICENSE, third-party-programs.txt and SECURITY.md files to custom_operations folder
> [Tokenizers] Add LICENSE to OpenVINO Tokenizers

- modules/custom_operations/user_ie_extensions/tokenizer/python/openvino_tokenizers/__init__.py
The wheel package can be installed using conda and at this case the extension will located in the lib subdir.
> [TOKENIZERS] Support of conda pip install

- modules/custom_operations/CMakeLists.txt
- modules/custom_operations/user_ie_extensions/tokenizer/CMakeLists.txt
- set default cmake default version (<Openvino Version>.<Extension Version>-<Commit Id>)
- set cpack version 
- disabled cpack source package
> [TOKENIZERS] Set cmake project version

- .ci/azure/windows.yml
- modules/custom_operations/pyproject.toml
Ported https://github.com/openvinotoolkit/openvino_contrib/pull/804
> [TOKENIZERS] Bump version to match OpenVINO master

- modules/custom_operations/user_ie_extensions/tokenizer/sentence_piece.cpp
Ported https://github.com/openvinotoolkit/openvino_contrib/pull/814
> [Tokenizers] Add WA for TF Text Sentencepiece Tokenizer (#814)

- .ci/azure/linux.yml
- .ci/azure/linux_cuda.yml
- .ci/azure/mac.yml
- modules/custom_operations/user_ie_extensions/tokenizer/CMakeLists.txt
See https://dev.azure.com/openvinoci/dldt/_build/results?buildId=680184&view=logs&j=0609cd82-f9f7-5e70-371c-89fca78031ab&t=746a4882-a379-5332-60d1-b0c4d02588ba&l=77
> Try to fix tokenizers on Linux

- modules/nvidia_plugin/src/ops/mvn.cpp
Switch from ngraph to ov shape utils.
Related to PR openvinotoolkit/openvino#22059
> [NVIDIA] Switch to ov shape utils

- .ci/azure/linux.yml
- .ci/azure/linux_cuda.yml
- .ci/azure/mac.yml
- modules/custom_operations/user_ie_extensions/tokenizer/CMakeLists.txt
Ported https://github.com/openvinotoolkit/openvino_contrib/pull/817
> [Tokenizers] Try to fix tokenizers on Linux

- .ci/azure/linux.yml
- .ci/azure/mac.yml
- .ci/azure/windows.yml
- modules/custom_operations/user_ie_extensions/complex_mul.cpp
- modules/custom_operations/user_ie_extensions/fft.cpp
- modules/custom_operations/user_ie_extensions/tokenizer/string_tensor_unpack.cpp
Required for https://github.com/openvinotoolkit/openvino/pull/22105
> Removed legacy API 1.0

- modules/custom_operations/user_ie_extensions/tokenizer/python/openvino_tokenizers/__init__.py
> [Tokenizers] Patch FrontEnd Init With Extension

- .github/ISSUE_TEMPLATE/good_first_issue.yml
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms
Copy of https://github.com/openvinotoolkit/openvino/blob/master/.github/ISSUE_TEMPLATE/good_first_issue.yml
> GFI template

- modules/nvidia_plugin/src/cuda_compiled_model.cpp
- modules/nvidia_plugin/src/cuda_infer_request.cpp
- modules/nvidia_plugin/src/cuda_plugin.cpp
- modules/nvidia_plugin/src/ops/result.cpp
- modules/nvidia_plugin/src/transformer/concat_transformation.cpp
- modules/nvidia_plugin/src/transformer/fuse_conv_biasadd_activation.cpp
- modules/nvidia_plugin/src/transformer/fuse_matmul_add.cpp
- modules/nvidia_plugin/src/transformer/matmul_transformations.cpp
- modules/nvidia_plugin/src/transformer/reduce_transformation.cpp
- Remove some legacy API header files
> Remove some legacy API header files

- modules/nvidia_plugin/src/cuda/device_pointers.hpp
- modules/nvidia_plugin/src/cuda/graph.cpp
- modules/nvidia_plugin/src/cuda/graph.hpp
- modules/nvidia_plugin/src/cuda/node_params.hpp
- modules/nvidia_plugin/src/kernels/insert.cu
- modules/nvidia_plugin/src/kernels/insert.hpp
- modules/nvidia_plugin/src/kernels/slice.cu
- modules/nvidia_plugin/src/kernels/slice.hpp
- modules/nvidia_plugin/tests/unit/cuda_graph_nodes_test.cpp
- *Add Transfer and Kernel Node Wrappers and NodeParams Structure to later be used in TensorIterator CUDA graph optimization*
- 122556
- 122563
> [NVIDIA] Add Transfer and Kernel Node Wrappers, NodeParams Structure

- .ci/azure/linux.yml
- .ci/azure/windows.yml
- modules/custom_operations/user_ie_extensions/tokenizer/CMakeLists.txt
- modules/custom_operations/user_ie_extensions/tokenizer/python/openvino_tokenizers/__init__.py
> [TOKENIZERS] Changed target name 

- modules/custom_operations/user_ie_extensions/tokenizer/python/README.md
> [Tokenizers] Add Cpack Instructions (#838)

- modules/nvidia_plugin/tests/functional/skip_tests_config.cpp
Disable ImportModelWithNullContextThrows test
CVS-128924
> Disable broken test

- modules/custom_operations/pyproject.toml
> [Tokenizers][SDL] Add minimal version for transformers library (#843)

- modules/nvidia_plugin/src/cuda_eager_topology_runner.cpp
- modules/nvidia_plugin/src/cuda_graph_context.hpp
- modules/nvidia_plugin/src/ops/subgraph.hpp
- modules/nvidia_plugin/src/ops/tensor_iterator.hpp
Resolving conflicts in https://github.com/openvinotoolkit/openvino_contrib/pull/755
> Cuda graph

- modules/custom_operations/user_ie_extensions/tokenizer/sentence_piece.cpp
> [Tokenizers][SDL] Throw Exception for Unexpected Type

- modules/openvino_code/package-lock.json
- modules/openvino_code/side-panel-ui/package.json
> [openvino_code] Updated vite version to 4.5.2

- modules/nvidia_plugin/tests/unit/CMakeLists.txt
- modules/nvidia_plugin/tests/unit/cuda_multi_graph_ti_test.cpp
Reverts openvinotoolkit/openvino_contrib#871
NVIDIA plugin failed in several places:
- https://github.com/openvinotoolkit/openvino/actions/runs/7840595080/job/21396025005
- https://github.com/openvinotoolkit/openvino/actions/runs/7840466815/job/21395453876
> Revert "Remove legacy test utils"

- modules/nvidia_plugin/tests/unit/cuda_multi_graph_ti_test.cpp
Second try of https://github.com/openvinotoolkit/openvino_contrib/pull/871
This time I didn't use template plugin directly.
> Remove legacy test utils

- modules/openvino_code/package-lock.json
- modules/openvino_code/package.json
- modules/openvino_code/server/pyproject.toml
- modules/openvino_code/shared/model.ts
Updated transformer version from 4.31.0 to 4.36.0 at: https://github.com/openvinotoolkit/openvino_contrib/blob/master/modules/openvino_code/server/pyproject.toml
> [Openvino code] fixed vulnerability issue - updated transformers version

- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/ov_finite_comparer.cpp
Required for https://github.com/openvinotoolkit/openvino/pull/22704
> Remove use of `ov_helpers.hpp`

- modules/nvidia_plugin/tests/unit/CMakeLists.txt
- modules/nvidia_plugin/tests/unit/cuda_multi_graph_test.cpp
Required for https://github.com/openvinotoolkit/openvino/pull/23084
> Get rid of `ov_models`

- modules/openvino_code/server/pyproject.toml
[CVS-133408](https://jira.devtools.intel.com/browse/CVS-133408)
> Bump up `fastapi` version

- modules/openvino_code/package-lock.json
- modules/openvino_code/package.json
- modules/openvino_code/shared/model.ts
- modules/openvino_code/side-panel-ui/src/components/sections/ServerSection/ModelSelect/ModelSelect.tsx
adding phi-2 model for code completion feature
> [OPENVINO_CODE] Add phi-2 model

- modules/nvidia_plugin/utils/shape-extractor/requirements.txt
Another place to bump jinja in addition to https://github.com/openvinotoolkit/openvino_contrib/commit/5243f86d2e5ef2d59a503ff911c966674a0f73d5
> Bump jinja in nvidia_plugin/utils/shape-extractor

- modules/openvino_code/package-lock.json
- modules/openvino_code/package.json
- modules/openvino_code/server/pyproject.toml
- modules/openvino_code/shared/model.ts
- modules/openvino_code/side-panel-ui/package.json
**Update dependencies:**
1. Updated OV version to 2024.1.0
2. Updated Vite to 4.5.3
3. Updated phi-2 model
> [OPENVINO-CODE]  Update OV version to 2024.1.0

- modules/nvidia_plugin/tests/functional/shared_tests_instances/single_layer_tests/generator/requirements.txt
- modules/nvidia_plugin/utils/shape-extractor/requirements.txt
> Update Jinja to 3.1.5 version

- .github/workflows/code_style.yml
- Update Java code style 3rdparty action
- Install JDK 21 before running the action
> [CI] Fix Java code style job
